### ISSUE TITLE
pyglove/backend.py: possible dependency on internal google vizier module?

### ISSUE THREAD

**Issue by ConnorBaker** [google/vizier#1031]
While trying to use Vizier with PyGlove (and running into #1029 and #1030), I also noticed

https://github.com/google/vizier/blob/e9e1671ada5970cb20e9417eb0a4efd47e1f590c/vizier/_src/pyglove/core.py#L32

which causes my script to fail with a `ModuleNotFoundError`:

```console
Traceback (most recent call last):
  File "/Users/connorbaker/Packages/ghc_hyperopt/./ghc_hyperopt/__main__.py", line 4, in <module>
    from vizier import pyglove as pg_vizier
  File "/Users/connorbaker/micromamba/envs/ghc_hyperopt/lib/python3.11/site-packages/vizier/pyglove/__init__.py", line 20, in <module>
    from vizier._src.pyglove.oss_vizier import init
  File "/Users/connorbaker/micromamba/envs/ghc_hyperopt/lib/python3.11/site-packages/vizier/_src/pyglove/oss_vizier.py", line 32, in <module>
    from vizier._src.pyglove import backend
  File "/Users/connorbaker/micromamba/envs/ghc_hyperopt/lib/python3.11/site-packages/vizier/_src/pyglove/backend.py", line 31, in <module>
    from vizier._src.pyglove import client
  File "/Users/connorbaker/micromamba/envs/ghc_hyperopt/lib/python3.11/site-packages/vizier/_src/pyglove/client.py", line 28, in <module>
    from vizier._src.pyglove import pythia as pg_pythia
  File "/Users/connorbaker/micromamba/envs/ghc_hyperopt/lib/python3.11/site-packages/vizier/_src/pyglove/pythia.py", line 29, in <module>
    from vizier._src.pyglove import core
  File "/Users/connorbaker/micromamba/envs/ghc_hyperopt/lib/python3.11/site-packages/vizier/_src/pyglove/core.py", line 32, in <module>
    from vizier.google import metadata_to_user
ModuleNotFoundError: No module named 'vizier.google'
```

The dependency was introduced as part of https://github.com/google/vizier/commit/bf576cdcedf1abcae948668b1e11d50afa4170ae, but I can't find it anywhere in the source tree.

Any suggestions?

**Comment by sagipe** [comment]
Thank you for the bug report, fixed in https://github.com/google/vizier/pull/1032

Best,
Sagi
