### ISSUE TITLE
Currently NSGA2 is broken when using SQL datastore

### ISSUE THREAD

**Issue by hello-eternity** [google/vizier#80]
Sorry for asking, I deployed oss vizier on my server. And sucessfully run the run_vizier_server.py. However when I run the run_vizier_client.py I got such error log on server:
```
E0708 13:08:56.978154 140386903254784 _server.py:445] Exception calling application: Currently NSGA2 is broken when using SQL datastore, due to needed metadata update changes.
Traceback (most recent call last):
  File "/root/anaconda3/envs/vizier/lib/python3.9/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/home/wxz/project/vizier/vizier/service/vizier_server.py", line 291, in SuggestTrials
    pythia_policy = policy_creator(study.study_spec.algorithm,
  File "/home/wxz/project/vizier/vizier/service/vizier_server.py", line 45, in policy_creator
    raise ValueError(
ValueError: Currently NSGA2 is broken when using SQL datastore, due to needed metadata update changes.
```
and the client error log like this,
```
I0708 13:08:56.962552 139991912334144 vizier_client.py:51] Securing channel to localhost:24956.
I0708 13:08:56.967267 139991912334144 vizier_client.py:55] Secured channel to localhost:24956.
I0708 13:08:56.973042 139991912334144 run_vizier_client.py:94] Client created with study name: owners/my_name/studies/cifar10
Traceback (most recent call last):
  File "/home/wxz/project/vizier/demos/run_vizier_client.py", line 117, in <module>
    app.run(main)
  File "/root/anaconda3/envs/vizier/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/anaconda3/envs/vizier/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/wxz/project/vizier/demos/run_vizier_client.py", line 98, in main
    suggestions = client.get_suggestions(
  File "/home/wxz/project/vizier/vizier/service/vizier_client.py", line 150, in get_suggestions
    operation = future.result()
  File "/root/anaconda3/envs/vizier/lib/python3.9/site-packages/grpc/_channel.py", line 722, in result
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: Currently NSGA2 is broken when using SQL datastore, due to needed metadata update changes."
        debug_error_string = "{"created":"@1657256936.978906103","description":"Error received from peer ipv4:127.0.0.1:24956","file":"src/core/lib/surface/call.cc","file_line":1067,"grpc_message":"Exception calling application: Currently NSGA2 is broken when using SQL datastore, due to needed metadata update changes.","grpc_status":2}"
>
```
Please give me some advice how can I sovle this.

**Comment by xingyousong** [comment]
Hi @hello-eternity, I've swapped NSGA2 with RANDOM_SEARCH in the demo in https://github.com/google/vizier/commit/9ca8b5a9c7af2b451e164f8707c711b393b5af21, since currently we're in the middle of a few migrations (which affects NSGA2). 

Hope this helps!
