### ISSUE TITLE
[Bug] suggest() of EagleStrategyDesigner will raise AttributeError: 'float' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by songlei00** [google/vizier#874]
My search space has two float parameters. When I use suggest() of EagleStrategyDesigner, I receive an AttributeError: 'float' object has no attribute 'flatten'. The full error log is as follows:

```
Traceback (most recent call last):
  File "test.py", line 54, in <module>
    suggestion = designer.suggest(count=1)[0]
  File "anaconda3/lib/python3.10/site-packages/vizier/_src/algorithms/designers/eagle_strategy/eagle_strategy.py", line 209, in suggest
    return self._scaler.unmap(scaled_suggestions)
  File "anaconda3/lib/python3.10/site-packages/vizier/pyvizier/converters/embedder.py", line 151, in unmap
    parameters[name] = param_converter.to_parameter_values(value)[0]
  File "anaconda3/lib/python3.10/site-packages/vizier/pyvizier/converters/core.py", line 697, in to_parameter_values
    return [self._to_parameter_value(v) for v in list(array.flatten())]
AttributeError: 'float' object has no attribute 'flatten'
```

I think it is because `value` parameter is considered as `ndarray` type, as annotated in `to_parameter_values` function in line 692 of `vizier/pyvizier/converters
/core.py`. But the value of the parameter is actually a float.

**Comment by qiuyiz** [comment]
Can you please past the code to replicate your setup?

**Comment by qiuyiz** [comment]
Thanks! This will be fixed on the next release!
